### PR TITLE
Make go binary smaller

### PR DESCRIPTION
**Pull request by luantak**
Added the -w ldflag to strip debug info from binary.
$ go tool link
...
-s  disable symbol table
...
-w  disable DWARF generation
...

### CODE REVIEW

**Comment by lu4p** [comment]
Of course also the println() function could be used for a more fair comparison which would halve the binary size. 
The funcionallity of fmt.Println() includes printing any type vs. println() only printing strings, much like the print functions from the other languages which are used.

**Review by dom96 — COMMENTED** [review]
what's the size difference?

**Comment by luantak** [comment]
about 1.4 MB vs 1.6 MB

**Comment by dom96** [comment]
See the "Criteria" in the readme. In fact, we should probably remove the existing Go compilation flag.

**Pull request closed without merging**
