### PR TITLE
Add Crystal

### PR DESCRIPTION
**Pull request by faustinoaq**
Hi @dom96 , I enjoy compiled languages like Nim and Crystal.

This PR adds Crystal to your awesome list.

I got this results:

```
-rwxr-xr-x 1 main main   43624 Aug 7 13:10 hello_nim
-rwxr-xr-x 1 main main  176912 Aug 7 13:10 hello_crystal
-rwxr-xr-x 1 main main  979458 Aug 7 13:10 hello_d
-rwxr-xr-x 1 main main  339352 Aug 7 13:10 hello_rust
-rwxr-xr-x 1 main main 1383900 Aug 7 13:10 hello_hs
-rwxr-xr-x 1 main main 1625987 Aug 7 13:10 hello_go
```

BTW, Thanks for Nim in Action :smile:

### CODE REVIEW

**Comment by dom96** [comment]
Thanks :)

**Comment by dom96** [comment]
Btw I didn't see you in #nim? Do you prefer Crystal?

**Comment by faustinoaq** [comment]
I'm new in Nim, I come from Python and C.

I found Crystal first. :sweat_smile:. I learnt Ruby thanks to Crystal.

BTW, Just missing add results to README.md and update https://nim-lang.org/features.html :sweat_smile:

**Comment by faustinoaq** [comment]
> Btw I didn't see you in #nim? Do you prefer Crystal?

I like boths, It's just like Python vs Ruby, too hard to choice :stuck_out_tongue_winking_eye:

**Comment by dom96** [comment]
Hah. Nah. The graphs are too busy as it is ;)

**Pull request merged**
